services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: template_db
    ports:
      - '5432:5432'

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - '8000:8000'
