services:
  postgres:
    container_name: cloud-notes
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: notes
      POSTGRES_PASSWORD: notes
      POSTGRES_DB: cloud_notes_db
    ports:
      - '7432:5432'

  redis:
    container_name: cloud-notes-redis
    image: redis:latest
    ports:
      - '7379:6379'

  dynamodb:
    container_name: cloud-notes-dynamodb
    image: amazon/dynamodb-local
    ports:
      - '7000:8000'
